#JavaChat client servers
#Mon Jun 01 14:58:28 GMT+07:00 2026
server.0.host=localhost
server.0.name=Localhost
server.0.port=5555
server.1.host=localhost
server.1.name=Server moi
server.1.port=5556
server.count=2
